//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestDRVtransGas.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.2.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Params.prmd")]
        public string sFileParam {
            get {
                return ((string)(this["sFileParam"]));
            }
            set {
                this["sFileParam"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Devices.devd")]
        public string sFileDev {
            get {
                return ((string)(this["sFileDev"]));
            }
            set {
                this["sFileDev"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000")]
        public decimal dmTimeResp {
            get {
                return ((decimal)(this["dmTimeResp"]));
            }
            set {
                this["dmTimeResp"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int iLeftForm {
            get {
                return ((int)(this["iLeftForm"]));
            }
            set {
                this["iLeftForm"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0 2")]
        public string asDataWritePar {
            get {
                return ((string)(this["asDataWritePar"]));
            }
            set {
                this["asDataWritePar"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("TempParName;DevDTSet")]
        public string asParameterName {
            get {
                return ((string)(this["asParameterName"]));
            }
            set {
                this["asParameterName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int iDataWritePar {
            get {
                return ((int)(this["iDataWritePar"]));
            }
            set {
                this["iDataWritePar"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int iParameterName {
            get {
                return ((int)(this["iParameterName"]));
            }
            set {
                this["iParameterName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0 2;0 481 487;0 4")]
        public string asData {
            get {
                return ((string)(this["asData"]));
            }
            set {
                this["asData"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int iData {
            get {
                return ((int)(this["iData"]));
            }
            set {
                this["iData"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int iTypeData {
            get {
                return ((int)(this["iTypeData"]));
            }
            set {
                this["iTypeData"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ERZ2004")]
        public string asDeviceStat {
            get {
                return ((string)(this["asDeviceStat"]));
            }
            set {
                this["asDeviceStat"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ERZ2004")]
        public string asDeviceWr {
            get {
                return ((string)(this["asDeviceWr"]));
            }
            set {
                this["asDeviceWr"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("600")]
        public int iHeightForm {
            get {
                return ((int)(this["iHeightForm"]));
            }
            set {
                this["iHeightForm"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1002")]
        public int iWidthForm {
            get {
                return ((int)(this["iWidthForm"]));
            }
            set {
                this["iWidthForm"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int iTopForm {
            get {
                return ((int)(this["iTopForm"]));
            }
            set {
                this["iTopForm"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.DateTime DTArchDay {
            get {
                return ((global::System.DateTime)(this["DTArchDay"]));
            }
            set {
                this["DTArchDay"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.DateTime DTArchHour {
            get {
                return ((global::System.DateTime)(this["DTArchHour"]));
            }
            set {
                this["DTArchHour"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.DateTime DTInterfer {
            get {
                return ((global::System.DateTime)(this["DTInterfer"]));
            }
            set {
                this["DTInterfer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.DateTime DTAlarm {
            get {
                return ((global::System.DateTime)(this["DTAlarm"]));
            }
            set {
                this["DTAlarm"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string asIPs {
            get {
                return ((string)(this["asIPs"]));
            }
            set {
                this["asIPs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("502")]
        public string asPort {
            get {
                return ((string)(this["asPort"]));
            }
            set {
                this["asPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string asIP {
            get {
                return ((string)(this["asIP"]));
            }
            set {
                this["asIP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string asCommand {
            get {
                return ((string)(this["asCommand"]));
            }
            set {
                this["asCommand"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("127.0.0.1;localhost;192.168.226.1;192.168.111.1")]
        public string IP {
            get {
                return ((string)(this["IP"]));
            }
            set {
                this["IP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("503")]
        public int iPort {
            get {
                return ((int)(this["iPort"]));
            }
            set {
                this["iPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int iTCPdeviceCurr {
            get {
                return ((int)(this["iTCPdeviceCurr"]));
            }
            set {
                this["iTCPdeviceCurr"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("500")]
        public int iIntervalScan {
            get {
                return ((int)(this["iIntervalScan"]));
            }
            set {
                this["iIntervalScan"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int iReverceValWr {
            get {
                return ((int)(this["iReverceValWr"]));
            }
            set {
                this["iReverceValWr"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("COM3")]
        public string asCOMport {
            get {
                return ((string)(this["asCOMport"]));
            }
            set {
                this["asCOMport"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("9600")]
        public string asBaud {
            get {
                return ((string)(this["asBaud"]));
            }
            set {
                this["asBaud"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public decimal dTimeoutBetwen {
            get {
                return ((decimal)(this["dTimeoutBetwen"]));
            }
            set {
                this["dTimeoutBetwen"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public decimal mComPort {
            get {
                return ((decimal)(this["mComPort"]));
            }
            set {
                this["mComPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("38400")]
        public string asBaudCom {
            get {
                return ((string)(this["asBaudCom"]));
            }
            set {
                this["asBaudCom"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("127.0.0.1")]
        public string asIPserver {
            get {
                return ((string)(this["asIPserver"]));
            }
            set {
                this["asIPserver"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("400")]
        public decimal dmSizeBufOut {
            get {
                return ((decimal)(this["dmSizeBufOut"]));
            }
            set {
                this["dmSizeBufOut"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("300")]
        public decimal dmWriteTimeout {
            get {
                return ((decimal)(this["dmWriteTimeout"]));
            }
            set {
                this["dmWriteTimeout"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public decimal dmRepeatWrite {
            get {
                return ((decimal)(this["dmRepeatWrite"]));
            }
            set {
                this["dmRepeatWrite"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int iIntervalSendFHPDev {
            get {
                return ((int)(this["iIntervalSendFHPDev"]));
            }
            set {
                this["iIntervalSendFHPDev"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int iParity {
            get {
                return ((int)(this["iParity"]));
            }
            set {
                this["iParity"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int iStopBits {
            get {
                return ((int)(this["iStopBits"]));
            }
            set {
                this["iStopBits"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8")]
        public int iDataBits {
            get {
                return ((int)(this["iDataBits"]));
            }
            set {
                this["iDataBits"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("прямое")]
        public string asDirBites {
            get {
                return ((string)(this["asDirBites"]));
            }
            set {
                this["asDirBites"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DataArToWr {
            get {
                return ((string)(this["DataArToWr"]));
            }
            set {
                this["DataArToWr"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int iIDstart {
            get {
                return ((int)(this["iIDstart"]));
            }
            set {
                this["iIDstart"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("дни")]
        public string DeltaDayHour {
            get {
                return ((string)(this["DeltaDayHour"]));
            }
            set {
                this["DeltaDayHour"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string as8n1To7e1 {
            get {
                return ((string)(this["as8n1To7e1"]));
            }
            set {
                this["as8n1To7e1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool b7bit {
            get {
                return ((bool)(this["b7bit"]));
            }
            set {
                this["b7bit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool bCalcBCC {
            get {
                return ((bool)(this["bCalcBCC"]));
            }
            set {
                this["bCalcBCC"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool bWordWrap {
            get {
                return ((bool)(this["bWordWrap"]));
            }
            set {
                this["bWordWrap"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("192.168.1.23")]
        public string asIPactive {
            get {
                return ((string)(this["asIPactive"]));
            }
            set {
                this["asIPactive"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10.10.195.169")]
        public string asIPpassive {
            get {
                return ((string)(this["asIPpassive"]));
            }
            set {
                this["asIPpassive"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("192.168.1.23;127.0.0.1")]
        public string asIPactiveList {
            get {
                return ((string)(this["asIPactiveList"]));
            }
            set {
                this["asIPactiveList"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10.10.195.169")]
        public string asIPpassiveList {
            get {
                return ((string)(this["asIPpassiveList"]));
            }
            set {
                this["asIPpassiveList"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("7777")]
        public int iPortPassive {
            get {
                return ((int)(this["iPortPassive"]));
            }
            set {
                this["iPortPassive"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("555")]
        public int iPortActive {
            get {
                return ((int)(this["iPortActive"]));
            }
            set {
                this["iPortActive"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("EK270")]
        public string asDevExch {
            get {
                return ((string)(this["asDevExch"]));
            }
            set {
                this["asDevExch"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string asDGBite8nTo7e {
            get {
                return ((string)(this["asDGBite8nTo7e"]));
            }
            set {
                this["asDGBite8nTo7e"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string asBtToStr {
            get {
                return ((string)(this["asBtToStr"]));
            }
            set {
                this["asBtToStr"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool bChDataAsHex {
            get {
                return ((bool)(this["bChDataAsHex"]));
            }
            set {
                this["bChDataAsHex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8")]
        public decimal dmSiseFontTCTtoTCT {
            get {
                return ((decimal)(this["dmSiseFontTCTtoTCT"]));
            }
            set {
                this["dmSiseFontTCTtoTCT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("192.168.1.23;127.0.0.1")]
        public string asIPactiveListComP {
            get {
                return ((string)(this["asIPactiveListComP"]));
            }
            set {
                this["asIPactiveListComP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string asParityTCTtoComP {
            get {
                return ((string)(this["asParityTCTtoComP"]));
            }
            set {
                this["asParityTCTtoComP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string asIPpassiveToComP {
            get {
                return ((string)(this["asIPpassiveToComP"]));
            }
            set {
                this["asIPpassiveToComP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string asStopBitsTCPtoComP {
            get {
                return ((string)(this["asStopBitsTCPtoComP"]));
            }
            set {
                this["asStopBitsTCPtoComP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string asComPortToComP {
            get {
                return ((string)(this["asComPortToComP"]));
            }
            set {
                this["asComPortToComP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string asBaudToComP {
            get {
                return ((string)(this["asBaudToComP"]));
            }
            set {
                this["asBaudToComP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string asDataBit {
            get {
                return ((string)(this["asDataBit"]));
            }
            set {
                this["asDataBit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string asZipDirs {
            get {
                return ((string)(this["asZipDirs"]));
            }
            set {
                this["asZipDirs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string asZipDirsExtr {
            get {
                return ((string)(this["asZipDirsExtr"]));
            }
            set {
                this["asZipDirsExtr"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string asZipDir {
            get {
                return ((string)(this["asZipDir"]));
            }
            set {
                this["asZipDir"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string asZipDirExtr {
            get {
                return ((string)(this["asZipDirExtr"]));
            }
            set {
                this["asZipDirExtr"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string asDevComPort {
            get {
                return ((string)(this["asDevComPort"]));
            }
            set {
                this["asDevComPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool bWordWrapByComPort {
            get {
                return ((bool)(this["bWordWrapByComPort"]));
            }
            set {
                this["bWordWrapByComPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("9")]
        public decimal dmSizeFontByComPort {
            get {
                return ((decimal)(this["dmSizeFontByComPort"]));
            }
            set {
                this["dmSizeFontByComPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int iPosComPortX {
            get {
                return ((int)(this["iPosComPortX"]));
            }
            set {
                this["iPosComPortX"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int iPosComPortY {
            get {
                return ((int)(this["iPosComPortY"]));
            }
            set {
                this["iPosComPortY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool bChangeVal_ComP {
            get {
                return ((bool)(this["bChangeVal_ComP"]));
            }
            set {
                this["bChangeVal_ComP"] = value;
            }
        }
    }
}
